# Azure Pipelines YAML

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: 'Build Stage'
  - deployment: VMDeploy
      displayName: Deploy to VM
      environment: 
      name: AzDevOpsVM
      resourceType: virtualMachine
      resourceName: WIN11 
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
    steps:
    - script: echo "Hello World"

- stage: Test
  displayName: 'Test Stage'
  jobs:
  - job: TestJob
    displayName: 'Test Job'
    steps:
    - task: AzureCLI@2
      displayName: 'Azure CLI Version Check'
      inputs:
        azureSubscription: 'Microsoft Partner Network(1)(0f00f93f-0899-453c-b398-7345b67daf9f)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az --version'
