trigger: 
- main

pool: 
   vmImage: windows-latest

jobs:
- deployment: VMDeploy
  displayName: Deploy to VM
  environment: 
    name: AzDevOpsVM
    resourceType: virtualMachine
    resourceName: WIN11 
  strategy:
    runOnce:
      deploy:   
          steps:
          - script: echo "Hello world"
