trigger:
- main

stages:
- stage: stage1
  displayName: 'Stage 1'
  jobs:
  - job: RunShellScriptOnWin11
    displayName: 'Run Shell Script on WIN11'
    pool:
      vmImage: 'windows-2019'
      demands:
      - Agent.Name -equals WIN11
    steps:
    - script: |
        echo "Hello World"
      displayName: 'Run Shell Script'


- stage: stage2
  displayName: 'Stage 2'
  jobs:
  - job: RunShellScriptOnUbuntu
    displayName: 'Run Shell Script on Ubuntu'
    pool:
      vmImage: 'ubuntu-latest'
      demands:
      - Agent.Name -equals ubuntu
    steps:
    - script: |
        echo "Hello World"
      displayName: 'Run Shell Script'

