stages:
- stage: Deploy
  pool: 
   name: SJM Agents
  jobs:
  - job: DeployJob1
    steps:
    - script: echo DeployJob1!
  - job: DeployJob2
    steps:
      - script: az -version
- stage: Build
  pool:
    name: SJM Agents
    jobs:
    steps:
      - script: az account list