stages:
- stage: Create
  jobs:
  - job: CreateAzureResources
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'Microsoft Partner Network(2)(0f00f93f-0899-453c-b398-7345b67daf9f)'
        subscriptionId: '0f00f93f-0899-453c-b398-7345b67daf9f'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'AzureDevOps'
        location: 'East US'
        templateLocation: 'Linked artifact'
        csmFile: 'https://github.com/Azure/azure-quickstart-templates/blob/master/demos/ubuntu-desktop-gnome-rdp/azuredeploy.json'
        csmParametersFile: 'https://github.com/Azure/azure-quickstart-templates/blob/master/demos/ubuntu-desktop-gnome-rdp/azuredeploy.parameters.json'
        deploymentMode: 'Incremental'
        deploymentName: 'AzureDevOps'
        deploymentOutputs: 'AzureDevOpsOut'

- stage: Build
  pool: 
   name: SJM Agents
  jobs:
  - job: BuildJob1
    steps:
    - script: echo DeployJob1
  - job: BuildJob2
    steps:
      - script: echo BuildJob2
- stage: Deploy
  pool:
    name: SJM Agents
  jobs:
  - job: DeployJob1
    steps:
      - script: echo DeployJob1
  - job: DepoloyJob2
    steps:
      - script: echo DeployJob2